{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "segway-sys-source-ms-azure-eventhub.secretname" . }}
  labels:
    {{- include "segway-sys-source-ms-azure-eventhub.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  AZURE_STORAGE_CONN_STR: {{ .Values.secret.data.AZURE_STORAGE_CONN_STR | b64enc }}
  AZURE_STORAGE_CONTAINER: {{ .Values.secret.data.AZURE_STORAGE_CONTAINER | b64enc }}
  EVENT_HUB_CONN_STR: {{ .Values.secret.data.EVENT_HUB_CONN_STR | b64enc }}
  EVENT_HUB_CONSUMER_GROUP: {{ .Values.secret.data.EVENT_HUB_CONSUMER_GROUP | b64enc }}
  EVENT_HUB_TRANSPORT_TYPE: {{ .Values.secret.data.EVENT_HUB_TRANSPORT_TYPE | default "default" | b64enc }}
{{- end }}
