{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "segway-sys-source-ms-azure-eventhub.serviceAccountName" . }}
  labels:
    {{- include "segway-sys-source-ms-azure-eventhub.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
